package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i route256/loms/internal/order_sender.OrderSender -o ./mocks/order_sender_minimock.go -n OrderSenderMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OrderSenderMock implements order_sender.OrderSender
type OrderSenderMock struct {
	t minimock.Tester

	funcSendOrder          func(ctx context.Context, orderId int64, orderStatus string) (err error)
	inspectFuncSendOrder   func(ctx context.Context, orderId int64, orderStatus string)
	afterSendOrderCounter  uint64
	beforeSendOrderCounter uint64
	SendOrderMock          mOrderSenderMockSendOrder
}

// NewOrderSenderMock returns a mock for order_sender.OrderSender
func NewOrderSenderMock(t minimock.Tester) *OrderSenderMock {
	m := &OrderSenderMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendOrderMock = mOrderSenderMockSendOrder{mock: m}
	m.SendOrderMock.callArgs = []*OrderSenderMockSendOrderParams{}

	return m
}

type mOrderSenderMockSendOrder struct {
	mock               *OrderSenderMock
	defaultExpectation *OrderSenderMockSendOrderExpectation
	expectations       []*OrderSenderMockSendOrderExpectation

	callArgs []*OrderSenderMockSendOrderParams
	mutex    sync.RWMutex
}

// OrderSenderMockSendOrderExpectation specifies expectation struct of the OrderSender.SendOrder
type OrderSenderMockSendOrderExpectation struct {
	mock    *OrderSenderMock
	params  *OrderSenderMockSendOrderParams
	results *OrderSenderMockSendOrderResults
	Counter uint64
}

// OrderSenderMockSendOrderParams contains parameters of the OrderSender.SendOrder
type OrderSenderMockSendOrderParams struct {
	ctx         context.Context
	orderId     int64
	orderStatus string
}

// OrderSenderMockSendOrderResults contains results of the OrderSender.SendOrder
type OrderSenderMockSendOrderResults struct {
	err error
}

// Expect sets up expected params for OrderSender.SendOrder
func (mmSendOrder *mOrderSenderMockSendOrder) Expect(ctx context.Context, orderId int64, orderStatus string) *mOrderSenderMockSendOrder {
	if mmSendOrder.mock.funcSendOrder != nil {
		mmSendOrder.mock.t.Fatalf("OrderSenderMock.SendOrder mock is already set by Set")
	}

	if mmSendOrder.defaultExpectation == nil {
		mmSendOrder.defaultExpectation = &OrderSenderMockSendOrderExpectation{}
	}

	mmSendOrder.defaultExpectation.params = &OrderSenderMockSendOrderParams{ctx, orderId, orderStatus}
	for _, e := range mmSendOrder.expectations {
		if minimock.Equal(e.params, mmSendOrder.defaultExpectation.params) {
			mmSendOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendOrder.defaultExpectation.params)
		}
	}

	return mmSendOrder
}

// Inspect accepts an inspector function that has same arguments as the OrderSender.SendOrder
func (mmSendOrder *mOrderSenderMockSendOrder) Inspect(f func(ctx context.Context, orderId int64, orderStatus string)) *mOrderSenderMockSendOrder {
	if mmSendOrder.mock.inspectFuncSendOrder != nil {
		mmSendOrder.mock.t.Fatalf("Inspect function is already set for OrderSenderMock.SendOrder")
	}

	mmSendOrder.mock.inspectFuncSendOrder = f

	return mmSendOrder
}

// Return sets up results that will be returned by OrderSender.SendOrder
func (mmSendOrder *mOrderSenderMockSendOrder) Return(err error) *OrderSenderMock {
	if mmSendOrder.mock.funcSendOrder != nil {
		mmSendOrder.mock.t.Fatalf("OrderSenderMock.SendOrder mock is already set by Set")
	}

	if mmSendOrder.defaultExpectation == nil {
		mmSendOrder.defaultExpectation = &OrderSenderMockSendOrderExpectation{mock: mmSendOrder.mock}
	}
	mmSendOrder.defaultExpectation.results = &OrderSenderMockSendOrderResults{err}
	return mmSendOrder.mock
}

// Set uses given function f to mock the OrderSender.SendOrder method
func (mmSendOrder *mOrderSenderMockSendOrder) Set(f func(ctx context.Context, orderId int64, orderStatus string) (err error)) *OrderSenderMock {
	if mmSendOrder.defaultExpectation != nil {
		mmSendOrder.mock.t.Fatalf("Default expectation is already set for the OrderSender.SendOrder method")
	}

	if len(mmSendOrder.expectations) > 0 {
		mmSendOrder.mock.t.Fatalf("Some expectations are already set for the OrderSender.SendOrder method")
	}

	mmSendOrder.mock.funcSendOrder = f
	return mmSendOrder.mock
}

// When sets expectation for the OrderSender.SendOrder which will trigger the result defined by the following
// Then helper
func (mmSendOrder *mOrderSenderMockSendOrder) When(ctx context.Context, orderId int64, orderStatus string) *OrderSenderMockSendOrderExpectation {
	if mmSendOrder.mock.funcSendOrder != nil {
		mmSendOrder.mock.t.Fatalf("OrderSenderMock.SendOrder mock is already set by Set")
	}

	expectation := &OrderSenderMockSendOrderExpectation{
		mock:   mmSendOrder.mock,
		params: &OrderSenderMockSendOrderParams{ctx, orderId, orderStatus},
	}
	mmSendOrder.expectations = append(mmSendOrder.expectations, expectation)
	return expectation
}

// Then sets up OrderSender.SendOrder return parameters for the expectation previously defined by the When method
func (e *OrderSenderMockSendOrderExpectation) Then(err error) *OrderSenderMock {
	e.results = &OrderSenderMockSendOrderResults{err}
	return e.mock
}

// SendOrder implements order_sender.OrderSender
func (mmSendOrder *OrderSenderMock) SendOrder(ctx context.Context, orderId int64, orderStatus string) (err error) {
	mm_atomic.AddUint64(&mmSendOrder.beforeSendOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmSendOrder.afterSendOrderCounter, 1)

	if mmSendOrder.inspectFuncSendOrder != nil {
		mmSendOrder.inspectFuncSendOrder(ctx, orderId, orderStatus)
	}

	mm_params := &OrderSenderMockSendOrderParams{ctx, orderId, orderStatus}

	// Record call args
	mmSendOrder.SendOrderMock.mutex.Lock()
	mmSendOrder.SendOrderMock.callArgs = append(mmSendOrder.SendOrderMock.callArgs, mm_params)
	mmSendOrder.SendOrderMock.mutex.Unlock()

	for _, e := range mmSendOrder.SendOrderMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendOrder.SendOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendOrder.SendOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmSendOrder.SendOrderMock.defaultExpectation.params
		mm_got := OrderSenderMockSendOrderParams{ctx, orderId, orderStatus}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendOrder.t.Errorf("OrderSenderMock.SendOrder got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendOrder.SendOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmSendOrder.t.Fatal("No results are set for the OrderSenderMock.SendOrder")
		}
		return (*mm_results).err
	}
	if mmSendOrder.funcSendOrder != nil {
		return mmSendOrder.funcSendOrder(ctx, orderId, orderStatus)
	}
	mmSendOrder.t.Fatalf("Unexpected call to OrderSenderMock.SendOrder. %v %v %v", ctx, orderId, orderStatus)
	return
}

// SendOrderAfterCounter returns a count of finished OrderSenderMock.SendOrder invocations
func (mmSendOrder *OrderSenderMock) SendOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendOrder.afterSendOrderCounter)
}

// SendOrderBeforeCounter returns a count of OrderSenderMock.SendOrder invocations
func (mmSendOrder *OrderSenderMock) SendOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendOrder.beforeSendOrderCounter)
}

// Calls returns a list of arguments used in each call to OrderSenderMock.SendOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendOrder *mOrderSenderMockSendOrder) Calls() []*OrderSenderMockSendOrderParams {
	mmSendOrder.mutex.RLock()

	argCopy := make([]*OrderSenderMockSendOrderParams, len(mmSendOrder.callArgs))
	copy(argCopy, mmSendOrder.callArgs)

	mmSendOrder.mutex.RUnlock()

	return argCopy
}

// MinimockSendOrderDone returns true if the count of the SendOrder invocations corresponds
// the number of defined expectations
func (m *OrderSenderMock) MinimockSendOrderDone() bool {
	for _, e := range m.SendOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendOrderCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendOrder != nil && mm_atomic.LoadUint64(&m.afterSendOrderCounter) < 1 {
		return false
	}
	return true
}

// MinimockSendOrderInspect logs each unmet expectation
func (m *OrderSenderMock) MinimockSendOrderInspect() {
	for _, e := range m.SendOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderSenderMock.SendOrder with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendOrderCounter) < 1 {
		if m.SendOrderMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to OrderSenderMock.SendOrder")
		} else {
			m.t.Errorf("Expected call to OrderSenderMock.SendOrder with params: %#v", *m.SendOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendOrder != nil && mm_atomic.LoadUint64(&m.afterSendOrderCounter) < 1 {
		m.t.Error("Expected call to OrderSenderMock.SendOrder")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderSenderMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSendOrderInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderSenderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderSenderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendOrderDone()
}
