version: '2'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-groups.yml:/etc/prometheus/alert-groups.yml

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alerts.yml:/etc/prometheus/alerts.yml
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped
    depends_on:
      - prometheus
    command:
      - '--config.file=/etc/prometheus/alerts.yml'
      - '--storage.path=/etc/alertmanager/data'

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./data:/var/lib/grafana
    links:
      - prometheus
